<a href="https://colab.research.google.com/github/Untick/InspectrumClinic_HR_gr2/blob/Abdrakhmanova-Guzel-folder/Abdrakhmanova-Guzel/week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Исследование датасета**

1) Датасет небольшой по размеру (579 анкет). Предполагаю, что его нужно будет расширять и дополнять.

2) Сам датасет скачивается файлом в формате xlsx. Так как с ним еще работают и он будет корректироваться, то предлагаю разместить его на гугл доках. Уровень доступа там можно корректировать. 

3) Данные в датасете не структурированы и в некоторых случаях заполнены с явными ошибками:
- колонка "Дата отклика" есть даты 03.03.223 и 12.23.23
- колонка "ЗП" содержит суммы в разной валюте (рубли, USD, EUR, KZT, KGS, ...)
- на 8 вакансий всего 11 подходящих анкет (причем эти анкеты только для 4 вакансий)
- какие требования по 8 вакансиям непонятно
- колонку "Город" разделить на колонки с городом/страной и колонкой/ами по готовности к командировкам и командировкам
- у части анкет нет ответа в колонке "Подходит - да/нет"
- в таблице нет колонок "Ключевые навыки", "Обо мне" (в ТЗ они упоминаются)

4) Необходимы критерии по всем 8 вакансиям

**Загрузка таблицы**

Загрузила файл "dataset.csv" в колаб

In [1]:
import pandas as pd

In [2]:
import chardet

enc = chardet.detect(open("dataset.xlsx", 'rb').read())

print(enc)

{'encoding': None, 'confidence': 0.0, 'language': None}

In [3]:
data = pd.read_excel("dataset.xlsx")
print(data.shape)
data.info()
data.head()

(579, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 579 entries, 0 to 578
Data columns (total 15 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Unnamed: 0                       579 non-null    int64
 1   Дата отклика                     579 non-null    object
 2   ФИО                              579 non-null    object
 3   Пол, возраст                     579 non-null    object
 4   ЗП                               579 non-null    object
 5   Ищет работу на должность         579 non-null    object
 6   Город                            579 non-null    object
 7   Занятость                        579 non-null    object
 8   График                           579 non-null    object
 9   Опыт ()                          579 non-null    object
 10  Последнее/нынешное место работы  579 non-null    object
 11  Последняя/нынешняя должность     579 non-null    object
 12  Образование и ВУЗ                579 non-null    object
 13  Обновление резюме                579 non-null    object
 14  Подходит - да/нет                500 non-null    object
dtypes: int64(1), object(14)
memory usage: 68.0+ KB

,Unnamed: 0,Дата отклика,ФИО,"Пол, возраст",ЗП,Ищет работу на должность,Город,Занятость,График,Опыт (),Последнее/нынешное место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,Подходит - да/нет
0,0,2023-02-23 00:00:00,Bessonova Mariya,Женщина,90 000 руб.,Growth Product Manager,"Индонезия, Не готова к переезду, не готова к к...","проектная работа, частичная занятость, полная ...",удаленная работа,Опыт работы —5 лет 10 месяцев,PT MYBALI APP GROUP,Менеджер по продукту,"Высшее, 2023, Нетоло́гия, 2014, Университет Ро...",23 февраля 2023 в 16:30,да
1,1,2023-01-11 00:00:00,Ефремова Екатерина Вячеславовна,Женщина,не указана,Growth Product Manager,"Москва, Готова к переезду, готова к командировкам",полная занятость,"удаленная работа, гибкий график, полный день",Опыт работы —11 лет 11 месяцев,Банк Открытие,Product owner трайб сбережения и инвестиции,"Высшее, 2022, GeekBrains, 2010, Московский худ...",8 февраля 2023 в 09:15,да
2,2,2023-02-27 00:00:00,Фролов Артур Михайлович,"Мужчина, 33 года, родился 23 августа 1989",150 000 руб.,Growth Product Manager,"Санкт-Петербург, Готов к переезду: Москва, гот...","проектная работа, частичная занятость, полная ...","удаленная работа, гибкий график, полный день",Опыт работы —7 лет 2 месяца,DIKIY LLC,Директор по маркетингу и бренд-менеджер,"Высшее, 2013, Санкт-Петербургский государствен...",28 февраля 2023 в 09:41,да
3,3,2023-01-11 00:00:00,Хозаев Расул Шагаманович,"Мужчина, 32 года, родился 7 декабря 1990",не указана,Growth Product Manager,"Москва, м. Молодежная, Хочу переехать, готов к...","стажировка, частичная занятость, полная занятость","удаленная работа, гибкий график, полный день",Опыт работы —8 лет 10 месяцев,WeInvest,Product Manager (team leader),"Магистр, 2014, Московский государственный техн...",24 января 2023 в 12:07,да
4,4,2023-01-11 00:00:00,Шадрин Олег Михайлович,"Мужчина, 26 лет, родился 21 февраля 1996",150 000 руб.,Growth Product Manager,"Пермь, Хочу переехать, готов к командировкам","проектная работа, частичная занятость, полная ...","удаленная работа, гибкий график, полный день",Опыт работы —5 лет 9 месяцев,Индивидуальное предпринимательство / частная п...,Product/Project manager,"Высшее, 2021, Российская академия народного хо...",6 февраля 2023 в 11:18,да

**Обработка датасета**

In [4]:
#Удаляем лишнее
data.dropna(axis=0, how='any')
data.drop(["Unnamed: 0", "Дата отклика", "Обновление резюме", "ФИО"], axis=1, inplace=True)
print(data.shape)

(579, 11)

In [5]:
# Убираем кодировку ASCII (\xa0 - неразрывный пробел, \n - перенос строки) в текстовых строках 

for i in range(data.shape[1]):
  for j in range(data.shape[0]):
    if isinstance(data.values[j][i], (int, float)) == False:
       data.values[j][i] = data.values[j][i].replace("\xa0", "")
       data.values[j][i] = data.values[j][i].replace("\n", "")

data.head()

,"Пол, возраст",ЗП,Ищет работу на должность,Город,Занятость,График,Опыт (),Последнее/нынешное место работы,Последняя/нынешняя должность,Образование и ВУЗ,Подходит - да/нет
0,Женщина,90 000 руб.,Growth Product Manager,"Индонезия, Не готова к переезду, не готова к к...","проектная работа, частичная занятость, полная ...",удаленная работа,Опыт работы —5 лет 10 месяцев,PT MYBALI APP GROUP,Менеджер по продукту,"Высшее, 2023, Нетоло́гия, 2014, Университет Ро...",да
1,Женщина,не указана,Growth Product Manager,"Москва, Готова к переезду, готова к командировкам",полная занятость,"удаленная работа, гибкий график, полный день",Опыт работы —11 лет 11 месяцев,Банк Открытие,Product owner трайб сбережения и инвестиции,"Высшее, 2022, GeekBrains, 2010, Московский худ...",да
2,"Мужчина, 33 года, родился 23 августа 1989",150 000 руб.,Growth Product Manager,"Санкт-Петербург, Готов к переезду: Москва, гот...","проектная работа, частичная занятость, полная ...","удаленная работа, гибкий график, полный день",Опыт работы —7 лет 2 месяца,DIKIY LLC,Директор по маркетингу и бренд-менеджер,"Высшее, 2013, Санкт-Петербургский государствен...",да
3,"Мужчина, 32 года, родился 7 декабря 1990",не указана,Growth Product Manager,"Москва, м. Молодежная, Хочу переехать, готов к...","стажировка, частичная занятость, полная занятость","удаленная работа, гибкий график, полный день",Опыт работы —8 лет 10 месяцев,WeInvest,Product Manager (team leader),"Магистр, 2014, Московский государственный техн...",да
4,"Мужчина, 26 лет, родился 21 февраля 1996",150 000 руб.,Growth Product Manager,"Пермь, Хочу переехать, готов к командировкам","проектная работа, частичная занятость, полная ...","удаленная работа, гибкий график, полный день",Опыт работы —5 лет 9 месяцев,Индивидуальное предпринимательство / частная п...,Product/Project manager,"Высшее, 2021, Российская академия народного хо...",да

In [6]:
# Копию делаем. Бекапы - это обязательно.
data2 = data.copy()

**Пол** 0/1 (1 - мужчина, 0 - женщина)

**Возраст** **ОНЕ на 8** (не указан - 0, от 1 до 17, от 18 до 24, от 25 до 35, от 36 до 44, от 45 до 59, от 60 до 74, от 75 и старше)  [0 0 0 0 0 1 0 0] (в колонке "Пол, возраст", *возраст может быть не указан*) 

**ЗП** **ОНЕ на 8** (не указан или 1, от 2 до 20000, от 20001 до 30000, от 30001 до 50000, от 50001 до 80000, от 80001 до 150000, от 150001 до 300000, от 300001 и выше) (переводить валюту в рубли) [0 0 0 0 0 1 0 0]  (*может быть не указана*)

**Ищет должность OHE на 8** (Growth Product Manager, HR-специалист, Product manager в Growth Hacking команду, Product Manager в команду HR, Product Manager в команду Финансового департамента, Product Marketing Manager в Growth Hacking команду, Project manager, Директор медицинской клиники)

**Город** **ОНЕ на 5** (Москва, Санкт-Петербург, Уфа, города-миллионники(Новосибирск Екатеринбург Нижний Новгород Казань Челябинск Омск Самара Ростов-на-Дону Красноярск Пермь Воронеж Волгоград), все остальные страны и города) [0 0 1 0 0]

Готовность к переезду, командировкам Multi(3x) (в колонке "Город", может быть не указан)

**Занятость Multi(6x)** (стажировка, волонтерство, проектная работа, частичная занятость, неполный рабочий день, полная занятость)

**График Multi(5x)** (вахтовый метод, удаленная работа, гибкий график, полный день, сменный график)

**Опыт ОНЕ на 11**

Последнее место работы BagofWords(10)

Последняя должность BagofWords(10)

**Образование и ВУЗ ОНЕ на 10 ** (Бакалавр;Высшее;Среднее специальное;Неоконченное высшее;Среднее;Среднее образование;Среднее специальное;Доктор наук;
Кандидат наук;Магистр

Подходит 0/1 (1 - да, 0 - нет)

Разделю на 8 категорий:

In [8]:
import datetime
import re
from tensorflow.keras import utils #Используем для to_categoricall

In [ ]:
# Функции для пола и возраста
def func_gender(arg):
  if "M" in arg:
    return 1
  else:
    return 0

def func_age(arg):
  phrase_split = arg.split(",")
  if len(phrase_split[1]) > 0:
    year = int(re.findall(r'\d+', phrase_split[1])[0])
  else:
    year = 0
  return year

# Функция определения категории возраста
def func_age_ohe(arg):
  if arg == 0:
    age_vector = 0
  elif 1 <= arg <= 17:
    age_vector = 1
  elif 18 <= arg <= 24:
    age_vector = 2
  elif 25 <= arg <= 35:
    age_vector = 3
  elif 36 <= arg <= 44:
    age_vector = 4
  elif 45 <= arg <= 59:
    age_vector = 5
  elif 60 <= arg <= 74:
    age_vector = 6
  else:
    age_vector = 7 
    
  return list(utils.to_categorical(age_vector, 8).astype('int'))

In [ ]:
# Зарплата
def func_salary(arg):
    num = arg
    # Убираем лишние знаки, получаем число
    if (type(num) == str):
        num = re.sub(' ','',num)
        num = re.sub('[а-яА-ЯёЁ]','',num)
        num = re.sub('[a-zA-Z]','',num)
        num = num.replace('.','')
        if num == "не указана":
          num = 1
            
        # Убираем цифры, получаем в какой валюте
        curr = re.sub('[0-9]','',arg)
        curr = curr.replace('.','').strip()
        if num == "не указана":
          curr == "руб"

        # Конвертируем в рубли, если валюта
        if curr == 'USD':
           num = float(num)*80
        elif curr == 'KZT':
           num = float(num)*0.18
        elif curr=='грн':
           num = float(num)*2.2
        elif curr=='UAH':
           num = float(num)*2.2
        elif curr=='белруб':
           num = float(num)*27.4
        elif curr=='BYN':
           num = float(num)*27.4
        elif curr=='EUR':
           num = float(num)*86
        elif curr=='KGS':
           num = float(num)*0.92
        elif curr=='сум':
           num = float(num)*0.007
        elif curr=='AZN':
           num = float(num)*47
    else:
      num = 1
      curr = "руб"

    salary = int(num) 
    
    return salary

# Функция определения категории зарплаты
def func_age_ohe(arg):
  if arg == 1:
    salary_vector = 0
  elif 2 <= arg <= 20000:
    salary_vector = 1
  elif 20001 <= arg <= 30000:
    salary_vector = 2
  elif 30001 <= arg <= 50000:
    salary_vector = 3
  elif 50001 <= arg <= 80000:
    salary_vector = 4
  elif 80001 <= arg <= 150000:
    salary_vector = 5
  elif 150001 <= arg <= 300000:
    salary_vector = 6
  else:
    salary_vector = 7 
    
  return list(utils.to_categorical(salary_vector, 8).astype('int'))

In [ ]:
# Должность
def func_vacancy(arg):
  if arg == "Growth Product Manager":
    vacancy_vector = 0
  elif arg == "HR-специалист":
    vacancy_vector = 1
  elif arg == "Product manager в Growth Hacking команду":
    vacancy_vector = 2
  elif arg == "Product Manager в команду HR":
    vacancy_vector = 3
  elif arg == "Product Manager в команду Финансового департамента":
    vacancy_vector = 4
  elif arg == "Product Marketing Manager в Growth Hacking команду":
    vacancy_vector = 5
  elif arg == "Project manager":
    vacancy_vector = 6
  elif arg == "Директор медицинской клиники":
    vacancy_vector = 7
  else:
    vacancy_vector = 2 
    
  return list(utils.to_categorical(vacancy_vector, 8).astype('int'))

# Город
def func_city(arg):
  millionCities = "Новосибирск Екатеринбург Нижний Новгород Казань Челябинск Омск Самара Ростов-на-Дону Красноярск Пермь Воронеж Волгоград"
  sarg=arg.split(',')
  for item in sarg:
    item= item.strip()
    if item == "Москва":          return [1, 0, 0, 0, 0]
    if item == "Санкт-Петербург": return [0, 1, 0, 0, 0]
    if item == "Уфа": return [0, 0, 1, 0, 0]
    if item in millionCities:     return [0, 0, 0, 1, 0]
  return [0, 0, 0, 0, 1]

# Занятость
def func_employment(arg):
  out= [0, 0, 0, 0, 0, 0]
  if ("стажировка" in arg):             out[0]=1
  if ("волонтерство" in arg):           out[1]=1
  if ("проектная работа" in arg):       out[2]=1
  if ("частичная занятость" in arg):    out[3]=1
  if ("неполный рабочий день" in arg):  out[4]=1
  if ("полная занятость" in arg):       out[5]=1
  return out

# График работы
def func_working_schedule(arg):
  out = [0, 0, 0, 0]
  if ("вахтовый метод" in arg):    out[0]=1
  if ("удаленная работа" in arg):  out[1]=1
  if ("гибкий график" in arg):     out[2]=1
  if ("полный день" in arg):       out[3]=1
  if ("сменный график" in arg):    out[4]=1
  return out

# Данные об образовании
def func_education(arg):
  out = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] #По умолчанию не указано
  if "Бакалавр" in arg or "Higher education" in arg:             out[0] = 1
  if "Высшее" in arg or "Higher education" in arg:               out[0] = 1
  if "Среднее специальное" in arg or "Higher education" in arg:  out[0] = 1
  if "Неоконченное высшее" in arg or "Higher education" in arg:  out[0] = 1
  if "Среднее" in arg or "Higher education" in arg:              out[0] = 1
  if "Среднее образование" in arg or "Higher education" in arg:  out[0] = 1
  if "Среднее специальное" in arg or "Higher education" in arg:  out[0] = 1
  if "Доктор наук" in arg:                                       out[1] = 1
  if "Кандидат наук" in arg:                                     out[2] = 1
  if "Магистр" in arg:                                           out[3] = 1

  return out

In [ ]:
# Данные об опыте работы
def getParameterExperience(arg):
  arg = str(arg)
  #Проверяем, если не пустая строка
  symbols = 0
  years = 0
  months = 0
  for s in arg:
    if (s != " "):
      symbols += 1
  
  #Находим индексы пробелов около фразы "опыт работы"
  if (symbols > 10):
      spacesIndexes = []
      index = 0
      while ((len(spacesIndexes) < 5) & (index < len(arg))):
          if (arg[index] == " "):
              spacesIndexes.append(index)
          index += 1

      years = 0
      months = 0
      if (arg[spacesIndexes[2]+1] != "м"):
         if (len(spacesIndexes) >= 3):
            yearsStr = arg[spacesIndexes[1]:spacesIndexes[2]] # Записываем в строку значение лет
            years = int(yearsStr)
      
         if (len(spacesIndexes) >= 5):
            monthsStr = arg[spacesIndexes[3]:spacesIndexes[4]] # Записываем в строку значение месяцев
            if(arg[spacesIndexes[2]+1] == "м"):
                months = int(monthsStr)
      else:
        if (len(spacesIndexes) >= 3):
          monthsStr = arg[spacesIndexes[1]:spacesIndexes[2]]
          months = int(monthsStr)
      
  return 12*years+months

# Категориальное представление опыта работы
def getParameterExperienceVector(arg):
  out = getParameterExperience(arg)
  outClass = 0
  if (out > 6): # если больше 6 месяцев
    outClass = 1
  if (out > 12): # если больше 12 месяцев
    outClass = 2
  if (out > 24): # если больше 24 месяцев
    outClass = 3
  if (out > 36): # если больше 36 месяцев
    outClass = 4
  if (out > 60): # если больше 60 месяцев
    outClass = 5
  if (out > 96): # если больше 96 месяцев
    outClass = 6
  if (out > 120): # если больше 120 месяцев
    outClass = 7
  if (out > 156): # если больше 156 месяцев
    outClass = 8
  if (out > 192): # если больше 192 месяцев
    outClass = 9 
  if (out > 240): # если больше 240 месяцев
    outClass = 10
  
  return list(utils.to_categorical(outClass, 11).astype('int'))

In [ ]:
# Извлекаем все параметры
def getAllParameters(val):

  
# Склеиваем все параметры в вектор  
  
  return out